# load the pachages
library(DOSE)
library(topGO)
library(clusterProfiler)
library(pathview)
library(ggplot2)
library(ggpubr)
library(dplyr)
library(bimaRt)
library(tidyr)
library(forcats)

# 1. Retrieve HIV with and without RNA expression
hiv_allsamples <- read.table("hiv_allsamples_jurkatchip.txt", header = T) #hiv_allsamples_jurkatchip.txt is available at xxx.

## SupT1 
SupT1_0ic_gene_S296_wRNA <- hiv_allsamples %>%
dplyr::filter(rep == "S296" & cat != "RE" & rna != 0) %>%
dplyr::select(gene_name, expscore) %>%
na.omit()

SupT1_0ic_gene_S296_woRNA <- hiv_allsamples %>%
dplyr::filter(rep == "S296" & cat != "RE" & rna == 0) %>%
dplyr::select(gene_name, expscore) %>%
na.omit()

SupT1_2ic_gene_S297_wRNA <- hiv_allsamples %>%
dplyr::filter(rep == "S297" & cat != "RE" & rna != 0) %>%
dplyr::select(gene_name, expscore) %>%
na.omit()

SupT1_2ic_gene_S297_woRNA <- hiv_allsamples %>%
dplyr::filter(rep == "S297" & cat != "RE" & rna == 0) %>%
dplyr::select(gene_name, expscore) %>%
na.omit()

SupT1_5ic_gene_S298_wRNA <- hiv_allsamples %>%
dplyr::filter(rep == "S298" & cat != "RE" & rna != 0) %>%
dplyr::select(gene_name, expscore) %>%
na.omit()

SupT1_5ic_gene_S298_woRNA <- hiv_allsamples %>%
dplyr::filter(rep == "S298" & cat != "RE" & rna == 0) %>%
dplyr::select(gene_name, expscore) %>%
na.omit()

SupT1_10ic_gene_S299_wRNA <- hiv_allsamples %>%
dplyr::filter(rep == "S299" & cat != "RE" & rna != 0) %>%
dplyr::select(gene_name, expscore) %>%
na.omit()

SupT1_10ic_gene_S299_woRNA <- hiv_allsamples %>%
dplyr::filter(rep == "S299" & cat != "RE" & rna == 0) %>%
dplyr::select(gene_name, expscore) %>%
na.omit()

## Jurkat  
Jurkat_0ic_gene_S300_wRNA <- hiv_allsamples %>%
dplyr::filter(rep == "S300" & cat != "RE" & rna != 0) %>%
dplyr::select(gene_name, expscore) %>%
na.omit()

Jurkat_0ic_gene_S300_woRNA <- hiv_allsamples %>%
dplyr::filter(rep == "S300" & cat != "RE" & rna == 0) %>%
dplyr::select(gene_name, expscore) %>%
na.omit()

Jurkat_2ic_gene_S301_wRNA <- hiv_allsamples %>%
dplyr::filter(rep == "S301" & cat != "RE" & rna != 0) %>%
dplyr::select(gene_name, expscore) %>%
na.omit()

Jurkat_2ic_gene_S301_woRNA <- hiv_allsamples %>%
dplyr::filter(rep == "S301" & cat != "RE" & rna == 0) %>%
dplyr::select(gene_name, expscore) %>%
na.omit()

Jurkat_5ic_gene_S302_wRNA <- hiv_allsamples %>%
dplyr::filter(rep == "S302" & cat != "RE" & rna != 0) %>%
dplyr::select(gene_name, expscore) %>%
na.omit()

Jurkat_5ic_gene_S302_woRNA <- hiv_allsamples %>%
dplyr::filter(rep == "S302" & cat != "RE" & rna == 0) %>%
dplyr::select(gene_name, expscore) %>%
na.omit()

Jurkat_10ic_gene_S303_wRNA <- hiv_allsamples %>%
dplyr::filter(rep == "S303" & cat != "RE" & rna != 0) %>%
dplyr::select(gene_name, expscore) %>%
na.omit()

Jurkat_10ic_gene_S303_woRNA <- hiv_allsamples %>%
dplyr::filter(rep == "S303" & cat != "RE" & rna == 0) %>%
dplyr::select(gene_name, expscore) %>%
na.omit()
